# отладка
#log-file=output.txt
#msg-level=all=trace

alang=rus,eng
slang=rus,eng
script-opts-append=modernz-language=ru

#osd-scale-by-window=yes
osd-font-size=20
script-opts-append=console-font_size=12
script-opts-append=console-scale_with_window=no
#osd-font="Consolas"
osd-font="Cascadia Code"
#osd-font="Courier New"

#cache=no
cache-secs=10

ytdl=no
autocreate-playlist=no
idle=yes
keep-open=always
keepaspect-window=yes
force-window=yes
save-position-on-quit=yes
autofit = 50%x50%
border=no

#watch-later-options=window-scale,window-maximized,volume,mute,audio-device,panscan,video-rotate,video-zoom,video-pan-x,video-pan-y,vid,aid,sid,secondary-sid
#screen = 1

hwdec=auto
vo=gpu
#vo=gpu-next

script-opts-append=modernz-zones_hover_mode=zones

script-opts-append=modernz-idlescreen=no
script-opts-append=modernz-icon_theme=material
script-opts-append=modernz-icon_style=filled
script-opts-append=modernz-keeponpause=yes
script-opts-append=modernz-fadein=yes
script-opts-append=modernz-title_font_size=20
script-opts-append=modernz-cache_info=yes
script-opts-append=modernz-cache_info_speed=yes
script-opts-append=modernz-cache_info_font_size=16
script-opts-append=modernz-show_chapter_title=no
script-opts-append=modernz-time_format=fixed
script-opts-append=modernz-persistentprogress=yes

script-opts-append=modernz-ontop_button=yes

script-opts-append=modernz-show_window_title=yes
script-opts-append=modernz-window_title=${title}
script-opts-append=modernz-window_title_font_size=20
script-opts-append=modernz-subtitles_button=no
script-opts-append=modernz-jump_more_amount=10
script-opts-append=modernz-download_button=no
script-opts-append=modernz-screenshot_button=yes
script-opts-append=modernz-loop_button=no
script-opts-append=modernz-loop_in_pause=no
script-opts-append=modernz-speed_button_click=0.25

# script-message-to modernz osc-hide
script-opts-append=modernz-playlist_mbtn_left_command=script-binding show-menu;
script-opts-append=modernz-playlist_mbtn_mid_command=script-binding select-channel-list-self;
script-opts-append=modernz-playlist_mbtn_ctrl_command=script-binding select-channel-list-self;
script-opts-append=modernz-playlist_mbtn_right_command=script-binding select-play-list-self;

script-opts-append=modernz-playlist_prev_mbtn_mid_command=script-binding select-channel-list-self;
script-opts-append=modernz-playlist_prev_mbtn_ctrl_command=script-binding select-channel-list-self;
script-opts-append=modernz-playlist_prev_mbtn_right_command=script-binding select-play-list-self;

script-opts-append=modernz-playlist_next_mbtn_mid_command=script-binding select-channel-list-self;
script-opts-append=modernz-playlist_next_mbtn_ctrl_command=script-binding select-channel-list-self;
script-opts-append=modernz-playlist_next_mbtn_right_command=script-binding select-play-list-self;
