#log-file=output.txt
#msg-level=all=trace

alang=rus,eng
slang=rus,eng
script-opts-append=modernz-language=ru

#osd-scale-by-window=yes
osd-font-size=24
script-opts-append=console-font_size=14
script-opts-append=console-scale_with_window=no
osd-font="Consolas"

#cache=no
cache-secs=10

ytdl=no
autocreate-playlist=no
idle=yes
keep-open=always
keepaspect-window=yes
force-window=yes
save-position-on-quit=yes
autofit = 50%x50%
border=no

#watch-later-options=window-scale,window-maximized,volume,mute,audio-device,panscan,video-rotate,video-zoom,video-pan-x,video-pan-y,vid,aid,sid,secondary-sid
#screen = 1

hwdec=auto
#vo=gpu
vo=gpu-next