zones_hover_mode=zones
idlescreen=no
icon_theme=material
icon_style=filled
keeponpause=no
fadein=yes
title_font_size=20
cache_info=yes
cache_info_speed=yes
cache_info_font_size=16
show_chapter_title=no
time_format=fixed
persistentprogress=yes
ontop_button=yes
show_window_title=yes
window_title=${title}
window_title_font_size=20
subtitles_button=no
jump_more_amount=10
download_button=no
screenshot_button=yes
loop_button=no
loop_in_pause=no
speed_button_click=0.25

playlist_mbtn_left_command=script-binding show-menu;
playlist_mbtn_mid_command=script-binding select-channel-list-self;
playlist_mbtn_ctrl_command=script-binding select-channel-list-self;
playlist_mbtn_right_command=script-binding select-play-list-self;

playlist_prev_mbtn_mid_command=script-binding select-channel-list-self;
playlist_prev_mbtn_ctrl_command=script-binding select-channel-list-self;
playlist_prev_mbtn_right_command=script-binding select-play-list-self;

playlist_next_mbtn_mid_command=script-binding select-channel-list-self;
playlist_next_mbtn_ctrl_command=script-binding select-channel-list-self;
playlist_next_mbtn_right_command=script-binding select-play-list-self;
